CREATE TABLE [dbo].[Matches] (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    [RoundId] INT NOT NULL,
    [RoomId] INT NOT NULL, 
    [OG_1]    INT NOT NULL,
    [OG_2]    INT NOT NULL,
    [OO_1]    INT NOT NULL,
    [OO_2]    INT NOT NULL,
    [CG_1]    INT NOT NULL,
    [CG_2]    INT NOT NULL,
    [CO_1]    INT NOT NULL,
    [CO_2]    INT NOT NULL,
    [OG_Points] INT NULL, 
    [OO_Points] INT NULL, 
    [CG_Points] INT NULL, 
    [CO_Points] INT NULL, 
    [OG_1_SpeakerPoints] INT NULL, 
    [OG_2_SpeakerPoints] INT NULL, 
    [OO_1_SpeakerPoints] INT NULL, 
    [OO_2_SpeakerPoints] INT NULL, 
    [CG_1_SpeakerPoints] INT NULL, 
    [CG_2_SpeakerPoints] INT NULL, 
    [CO_1_SpeakerPoints] INT NULL, 
    [CO_2_SpeakerPoints] INT NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CHECK ([OG_Points] IS NULL OR ((0)<=[OG_Points] AND [OG_Points]<=(3))),
    CHECK ([OO_Points] IS NULL OR ((0)<=[OO_Points] AND [OG_Points]<=(3))),
    CHECK ([CG_Points] IS NULL OR ((0)<=[CG_Points] AND [OG_Points]<=(3))),
    CHECK ([CO_Points] IS NULL OR ((0)<=[CO_Points] AND [OG_Points]<=(3))),
    CHECK ([OG_Points] IS NULL OR [OO_Points] IS NULL OR [CG_Points] IS NULL OR [OG_Points] IS NULL OR (([OG_Points] + [OO_Points] + [CG_Points] + [CO_Points]) = 6)),
    CHECK ([OG_1_SpeakerPoints] IS NULL OR ((60) <= [OG_1_SpeakerPoints] AND [OG_1_SpeakerPoints] <= (90))),
    CHECK ([OG_2_SpeakerPoints] IS NULL OR ((60) <= [OG_2_SpeakerPoints] AND [OG_2_SpeakerPoints] <= (90))),
    CHECK ([OO_1_SpeakerPoints] IS NULL OR ((60) <= [OO_1_SpeakerPoints] AND [OO_1_SpeakerPoints] <= (90))),
    CHECK ([OO_2_SpeakerPoints] IS NULL OR ((60) <= [OO_2_SpeakerPoints] AND [OO_2_SpeakerPoints] <= (90))),
    CHECK ([CG_1_SpeakerPoints] IS NULL OR ((60) <= [CG_1_SpeakerPoints] AND [CG_1_SpeakerPoints] <= (90))),
    CHECK ([CG_2_SpeakerPoints] IS NULL OR ((60) <= [CG_2_SpeakerPoints] AND [CG_2_SpeakerPoints] <= (90))),
    CHECK ([CO_1_SpeakerPoints] IS NULL OR ((60) <= [CO_1_SpeakerPoints] AND [CO_1_SpeakerPoints] <= (90))),
    CHECK ([CO_2_SpeakerPoints] IS NULL OR ((60) <= [CO_2_SpeakerPoints] AND [CO_2_SpeakerPoints] <= (90))),
    CONSTRAINT [FK_Matches_CG_1] FOREIGN KEY ([CG_1]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_CG_2] FOREIGN KEY ([CG_2]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_CO_1] FOREIGN KEY ([CO_1]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_CO_2] FOREIGN KEY ([CO_2]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_OG_1] FOREIGN KEY ([OG_1]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_OG_2] FOREIGN KEY ([OG_2]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_OO_1] FOREIGN KEY ([OO_1]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_OO_2] FOREIGN KEY ([OO_2]) REFERENCES [dbo].[Players] ([Id]),
    CONSTRAINT [FK_Matches_Round] FOREIGN KEY ([RoundId]) REFERENCES [dbo].[Rounds] ([Id]), 
    CONSTRAINT [FK_Matches_Room] FOREIGN KEY ([RoomId]) REFERENCES [dbo].[Rooms] ([Id])
);

